version: "3.8"
services:

  postgres-svc:

    image: postgres:12

    restart: always
    container_name: postgres-container
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./public.sql:/docker-entrypoint-initdb.d/dump.sql

  api-svc:

    image: chentochea/api-image:v1
    container_name: api-container
    restart: always
    # build: 
    #   context: ./apps/api
    #   dockerfile: Dockerfile
    ports:
      - "8082:3000"
    depends_on:
      - postgres-svc
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  client-svc:

    image: chentochea/client-image:v1
    container_name: client-container
    restart: always
    # build: 
    #   context: ./apps/client
    #   dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - api-svc
      - postgres-svc

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
